spring.application.name=quickStart
spring.datasource.url=jdbc:postgresql://localhost:5433/employee-sys
# Tells Hibernate how to translate Java entities into PostgreSQL SQL syntax
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Controls database schema generation (create, create-drop, validate, update, none)
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=postgres
spring.datasource.password=IElnafad01225942404
spring.main.allow-circular-references=true
# Prints executed SQL queries to your console (great for debugging)
#spring.jpa.show-sql=true
## Formats the printed SQL so it is easy to read
#spring.jpa.properties.hibernate.format_sql=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
SIGNING_MAIL=http://localhost:8080/auth/signup
JWT_SECRET=d11111b9dbf107c001c82075363a72e6bb7cf675a9fda3b2435c80281e7d2ec4
